### ISSUE TITLE
头发抽搐bug修复方案

### ISSUE THREAD

**Issue by dfdyz** [asuka-mio/KAIMyEntitySaba#1]
BUG产生原因：当只有最底层的动作活跃的时候（其它层都是nullptr）原动画更新逻辑就没有任何问题
当复数层的动画活跃的时候，前一层更新了动画帧（假设这时候是站立IDLE），更新物理帧头发是按照你站立时候来算的，下一层更新动画帧（假设这一层是弯腰）并叠加，这时候动画骨骼就是呈现弯腰姿态，然后（bug产生）再次更新物理帧，是按照从站立突变到弯腰的过程来计算物理帧的，开始拉扯刚体，之后再到下一个更新周期的时候，前一层又将动画骨骼设置为站立姿态，这时候物理帧更新就会进行从弯腰到站立过程的计算......如此循环就会导致层与层之间动作不一致的时候，发生刚体争抢，表现为头发衣服等抽搐并有明显的往某一个特定点拉扯的现象

解决方法：在updatemodel的时候仅在动画活跃的最上层（最后一个有动画的层）更新物理帧

具体位置
KAIMyEntitySaba.cpp
修改这个方法
void KAIMyEntitySaba::UpdateModel(Model* model)
{
	int maxAnim = 0;
	double deltaTime = saba::GetTime() - model->prevSabaTime;
	model->prevSabaTime = saba::GetTime();
	double elapsed = deltaTime;
	if (elapsed > PHYSICS_ELAPSED)
		elapsed = PHYSICS_ELAPSED;

	for (size_t i = 0; i < model->vmdAnimCount; ++i)
	{
		auto vmdAnim = model->vmdAnims[i];
		if (vmdAnim != nullptr)
		{
			maxAnim = i;
		}
	}

	model->mmdModel->BeginAnimation();
	for (size_t i = 0; i < model->vmdAnimCount; ++i)
	{
		auto vmdAnim = model->vmdAnims[i];
		if (vmdAnim != nullptr)
		{
			double animTime = model->animTimes[i] + deltaTime;
			if (animTime * FPS > vmdAnim->GetMaxKeyTime())
				animTime = 0.0;
			model->animTimes[i] = animTime;

			if (i == maxAnim)
			{
				model->mmdModel->UpdateAllAnimation(vmdAnim, animTime * FPS, elapsed);
			}
			else
			{
				model->mmdModel->UpdateAnimation(vmdAnim, animTime * FPS);
			}

		}
	}
	model->mmdModel->EndAnimation();
	model->mmdModel->Update();
}

MMDModel.cpp
添加这个重载
void MMDModel::UpdateAnimation(VMDAnimation* vmdAnim, float vmdFrame)
{
	if (vmdAnim != nullptr)
	{
		vmdAnim->Evaluate(vmdFrame);
	}

	UpdateMorphAnimation();
	UpdateNodeAnimation(false);
}

Github的排版好难用

**Comment by asuka-mio** [comment]
好的，感谢解决方案，这就修进去
